### PR TITLE
Beat Saber 0.12.0p1 compatibility

### PR DESCRIPTION
**Pull request by Zingabopp**
Everything appears to be working for 0.12.0p1. It's the first pull request I've done, so I'm not exactly sure what the best practices are. If you can, you'll probably want to only take the .cs files because somewhere along the line VS2017's Intellisense stopped working (everything still compiles, but it's really annoying).

### CODE REVIEW

**Comment by opl-** [comment]
I'll look over it when I have some time; busy week. Thanks!

**Comment by opl-** [comment]
First and most importantly, your editor changed the formatting from tabs to spaces, which makes the diff very difficult to read - even lines you didn't modify are marked as modified. That makes it difficult to tell what was actually changed in your commit and makes it impossible for git to perform some actions on those files. Always make sure your commits only change the lines you actually changed.

Additionally your PR doesn't include the latest changes from the master branch. You effectively reverted [the move of websocket-sharp.dll to a different directory](https://github.com/opl-/beatsaber-http-status/pull/8/files#diff-d21d08844ffbd8006de0a3b62163f519L109) (and possibly others? - hard to tell due to indentation changes). Worth noting here is issue #6 which points out that as of [commit `f22d7b`](https://github.com/opl-/beatsaber-http-status/commit/f22d7b25f8a70c58054d67647744d9717833c19a) obstacle entering and exiting detection has been broken, which I was unable to create a fix for since then and should be reverted or fixed before the next release.

Lastly, your PR changes relative paths within the project to absolute paths on your system, which will not work for other people. The project uses relative paths with the intention of the correct files either being symlinked from their relative paths to the correct paths or simply copied. Your PR creates the file [BeatSaberHTTPStatusPlugin.csproj.user](https://github.com/opl-/beatsaber-http-status/pull/8/files#diff-314bc66a139ab2bad1c77613ae0fdac3) which upon a quick search appears to be the file where such overrides could also take place, which might be worth looking into. Obviously, your commits should not change configuration like this either.

Your commit also changes the .sln file and, admittedly, I'm not sure if those changes affect anything, which is why I'd once again recommend you don't include those changes in your commits, unless someone can explain what the `GlobalSection(SolutionProperties) = preSolution` and `GlobalSection(ExtensibilityGlobals) = postSolution` sections do. The latter seems to point to a GUID that doesn't exist anywhere else which makes me believe it could once again be a user specific thing.

Please fix the above issues (especially the one changing the indentation) - I won't be able to merge this PR until those are resolved. I will test the code changes themselves in the next few days when I have access to a Vive.

I hope the above explanations will help you understand how to improve your PRs in the future and thanks again for taking your time to patch the mod for the new release.

**Comment by Zingabopp** [comment]
I Think I've got everything fixed now. Let me know if there's anything else.

**Comment by opl-** [comment]
Retroactively posting this here:

The `GameStatus` object is supposed to only contain primitive values to make it easy to make a clone of it in case the state needs to be preserved without making it impossible to add new changes to it. I know it's not obvious due to lack of documentation from me, but still letting you know for the future.

**Pull request merged**
