### PR TITLE
Feature/fix bsipa4 and 1.8.0 compat

### PR DESCRIPTION
**Pull request by ErisApps**
This PR supposedly fixes the mod for BSIPA 4 and version 1.8.0 of Beat Saber.
Some basic testing shows that it should work, but I'll test it more thoroughly after sleep. 😴 
(Therefor marking this PR as a draft)

### CODE REVIEW

**Comment by ErisApps** [comment]
PR should be good to go, a friend of mine confirmed that it should work as it should.

**Comment by opl-** [comment]
Thanks for the PR, I'll try to test it independently too before merging.

**Comment by Gordin** [comment]
Hi, I found this pull request yesterday because I need this for recording and I just wanted to confirm that this does indeed work.
I compiled from this branch and tested with BSIPA 4.0.3 and Beat Saber 1.8.0.

**Comment by rynan4818** [comment]
Hi, I have modified http-status to store my records in a SQLite3 database and create a tool that automatically cuts recorded videos.
I took this pull request and tested it on BS 1.8.0 and BSIPA4 with no problems.
https://drive.google.com/drive/folders/1k8eXDRLc-SdtE7jqyPho7iaygVa2Zz26?usp=sharing

**Comment by opl-** [comment]
Right, I won't have an HMD for a few other days and the person who usually tests it with me still hasn't tested it. That said, I think this is enough people confirming that it works to release it, so I'll get on that right now.

As for @rynan4818, if you want the tool to be listed on the wiki, please put it up for example in a new GitHub repository and open a new issue with a link to it. I'd be happy to add it to the list then.

**Comment by rynan4818** [comment]
Okay.
I still don't know how to use github, but I would like to study and post this weekend.

**Pull request merged**
